dist: xenial

language: haxe

haxe:
  - "4.0.0-rc.2"

before_install:
  # libraries used for testing
  - sudo apt-get install -y libcairo2 libpng-dev libjpeg-turbo8-dev libvorbis-dev libopenal-dev libsdl2-dev libmbedtls-dev libuv1-dev
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0 /usr/lib/x86_64-linux-gnu/libturbojpeg.so
  # dependencies
  - ./script/travis_install_libffi.sh
  - ./script/travis_install_hashlink.sh

install:
  - yes | haxelib install hxcpp
  - yes | haxelib install test.hxml

script:
  - ./script/make_examplelib.sh
  - ./script/make_callfunc.sh
  - haxe hxml/test.cpp.hxml
  - haxe hxml/test.hl.hxml
  - ./script/out_cpp_run.sh
  - ./script/out_hl_run.sh
