jobs:
  - job: nix
    strategy:
      matrix:
        linux:
          IMAGE: 'ubuntu-18.04'
          PLATFORM: linux-x86-64
          LIBFFI_LIB_PATH: "/usr/local/lib/libffi.so"
          LIBFFI_INCLUDE_PATH: "/usr/local/include/"
        mac:
          IMAGE: 'macos-10.13'
          PLATFORM: macos
          LIBFFI_LIB_PATH: "/usr/local/lib/libffi.dylib"
          LIBFFI_INCLUDE_PATH: "/usr/local/include/"

    pool:
      vmImage: $(IMAGE)
    steps:
      # Runtimes and dependencies
      - script: script/get_libffi.sh download $(PLATFORM)
      - script: script/get_libffi.sh install $(PLATFORM)
      - script: script/get_neko_bin.sh download $(PLATFORM)
      - script: script/get_neko_bin.sh install $(PLATFORM)
      - script: script/get_haxe_bin.sh download $(PLATFORM)
      - script: script/get_haxe_bin.sh install $(PLATFORM)
      - script: |
          sudo apt-get update
          sudo apt-get install libpng-dev libturbojpeg-dev libvorbis-dev libopenal-dev libsdl2-dev libmbedtls-dev libuv1-dev
        condition: and(
            succeeded(),
            eq(variables['Agent.OS'], 'Linux')
          )
      - script: script/get_hashlink.sh download $(PLATFORM)
      - script: brew bundle
        workingDirectory: out/hashlink/
        condition: and(
            succeeded(),
            eq(variables['Agent.OS'], 'Darwin')
          )
      - script: script/get_hashlink.sh install $(PLATFORM)

      # Haxe dependencies
      - script: haxelib --always --quiet install hxcpp
      - script: haxelib --always --quiet install hashlink
      - script: haxelib --always --quiet install test.hxml

      - template: script/azure-pipeline-templates/install_cmake.yml

      # Unit test files
      - script: brew install cairo
        condition: and(
            succeeded(),
            eq(variables['Agent.OS'], 'Darwin')
          )

      # Build unit tests
      - script: mkdir -p out/
      - script: cmake .. -DCMAKE_BUILD_TYPE=Debug
          -DLIBFFI_INCLUDE_PATH:PATH=$(LIBFFI_INCLUDE_PATH)
          -DLIBFFI_LIB_PATH:FILEPATH=$(LIBFFI_LIB_PATH)
        workingDirectory: out/
      - script: cmake --build . --config Debug
        workingDirectory: out/
      - script: haxe hxml/test.cpp.hxml -D callfunc_unit_test
      - script: haxe hxml/test.hl.hxml -D callfunc_unit_test
      - script: haxe hxml/test.hl.c.hxml -D callfunc_unit_test
      - script: gcc -g -o out/hl/test/test out/hl/test/test.c -I out/hl/test/ -std=c11 -lhl -lm out/callfunc/callfunc.hdll
      - script: haxe hxml/example_curl.cpp.hxml -D callfunc_unit_test
      - script: haxe hxml/example_curl.hl.hxml -D callfunc_unit_test
      - script: haxe hxml/example_random.cpp.hxml -D callfunc_unit_test
      - script: haxe hxml/example_random.hl.hxml -D callfunc_unit_test

      # Run unit tests
      - script: source script/export_ld_path.sh && ./out/cpp/TestAll-debug
      - script: source script/export_ld_path.sh && hl out/hl/test.hl
      - script: source script/export_ld_path.sh && out/hl/test/test

      # Build release library
      - script: mkdir -p out-release/
      - script: cmake .. -DCMAKE_BUILD_TYPE=Release
          -DLIBFFI_INCLUDE_PATH:PATH=$(LIBFFI_INCLUDE_PATH)
          -DLIBFFI_LIB_PATH:FILEPATH=$(LIBFFI_LIB_PATH)
        workingDirectory: out-release/
      - script: cmake --build . --config Release
        workingDirectory: out-release/

      # Publish releases
      - publish: out-release/callfunc/callfunc.hdll
        artifact: callfunc-hdll-$(PLATFORM)
      - publish: $(LIBFFI_LIB_PATH)
        artifact: libffi-$(PLATFORM)

  - job: windows
    strategy:
      matrix:
        windows:
          IMAGE: 'windows-2019'
          PLATFORM: windows-x86
          ARCH_NAME: x86
          MINGW_W64: c:/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/i686-w64-mingw32-gcc.exe
        # windows64:
        #   IMAGE: 'windows-2019'
        #   PLATFORM: windows-x86-64
        #   ARCH_NAME: x64
        #   MINGW_W64: c:/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/x86_64-w64-mingw32-gcc.exe
    pool:
      vmImage: $(IMAGE)
    steps:
      # Runtimes and dependencies
      - bash: script/get_libffi.sh install $(PLATFORM)
      - bash: script/get_neko_bin.sh download $(PLATFORM)
      - bash: script/get_neko_bin.sh install $(PLATFORM)
      - bash: script/get_haxe_bin.sh download $(PLATFORM)
      - bash: script/get_haxe_bin.sh install $(PLATFORM)
      - bash: script/get_mingw_bin.sh download $(PLATFORM)
      - bash: script/get_mingw_bin.sh install $(PLATFORM)
      # - task: Cache@2
      #   inputs:
      #     key: vcpkg | $(PLATFORM) | v1
      #     path: c:/vcpkg/
      #     cacheHitVar: CACHE_RESTORED_vcpkg
      # - script: vcpkg.exe install
      #     fmt:$(ARCH_NAME)-windows
      #     openal-soft:$(ARCH_NAME)-windows
      #     sdl2:$(ARCH_NAME)-windows
      #     mbedtls:$(ARCH_NAME)-windows
      #     libuv:$(ARCH_NAME)-windows
      #     cairo:$(ARCH_NAME)-windows
      #   condition: and(
      #       succeeded(),
      #       ne(variables.CACHE_RESTORED_vcpkg, 'true')
      #     )
      # - bash: script/get_hashlink.sh download $(PLATFORM)
      # - bash: patch -p1 --binary < "../../script/hashlink_sdl.patch"
      #   workingDirectory: out/hashlink/
      # - bash: script/get_hashlink.sh install $(PLATFORM)
      - bash: script/get_hashlink_bin.sh download $(PLATFORM)
      - bash: script/get_hashlink_bin.sh install $(PLATFORM)

      # Haxe dependencies
      - script: haxelib --always --quiet install hxcpp
      - script: haxelib --always --quiet install hashlink
      - script: haxelib --always --quiet install test.hxml

      # Build unit tests
      - bash: mkdir -p out/
      - powershell: cmake .. -DCMAKE_BUILD_TYPE=Debug
          -DHL_INCLUDE_PATH:PATH=../hashlink/src/
          -DHL_LIB_PATH:FILEPATH=c:\hl\libhl.lib
          -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT"\scripts\buildsystems\vcpkg.cmake
        workingDirectory: out/
      - script: cmake --build . --config Debug
        workingDirectory: out/
      - script: echo "##vso[task.prependpath]out/callfunc/Debug/"
      - script: haxe hxml/test.cpp.hxml -D callfunc_unit_test
      - script: haxe hxml/test.hl.hxml -D callfunc_unit_test
      - script: haxe hxml/test.hl.c.hxml -D callfunc_unit_test
      ## TODO:
      - script: $(MINGW_W64) -g -o out/hl/test/test out/hl/test/test.c -I out/hl/test/ -std=c11 -lhl -lm out/callfunc/callfunc.hdll
      - script: haxe hxml/example_curl.cpp.hxml -D callfunc_unit_test
      - script: haxe hxml/example_curl.hl.hxml -D callfunc_unit_test
      - script: haxe hxml/example_random.cpp.hxml -D callfunc_unit_test
      - script: haxe hxml/example_random.hl.hxml -D callfunc_unit_test

      # Run unit tests
      - script: ./out/cpp/TestAll-debug
      - script: hl out/hl/test.hl
      - script: out/hl/test/test

      # Build release library
      - bash: mkdir -p out-release/
      - powershell: cmake .. -DCMAKE_BUILD_TYPE=Release
          -DHL_INCLUDE_PATH:PATH=../hashlink/src/
          -DHL_LIB_PATH:FILEPATH=c:\hl\libhl.lib
          -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT"\scripts\buildsystems\vcpkg.cmake
        workingDirectory: out-release/
      - script: cmake --build . --config Release
        workingDirectory: out-release/

      # Publish releases
      - publish: out-release/callfunc/Release/callfunc.hdll
        artifact: callfunc-hdll-$(PLATFORM)
      - publish: out-release/callfunc/Release/libffi.dll
        artifact: libffi-$(PLATFORM)

  - job: emscripten_test
    pool:
      vmImage: ubuntu-18.04
    steps:
      - script: script/get_neko_bin.sh download linux-x86-64
      - script: script/get_neko_bin.sh install linux-x86-64
      - script: script/get_haxe_bin.sh download linux-x86-64
      - script: script/get_haxe_bin.sh install linux-x86-64
      - template: script/azure-pipeline-templates/install_cmake.yml
      - script: script/get_emsdk.sh
      - script: script/get_chromedriver.sh
      - script: python3 -m pip install selenium --user
      - script: cmake .. -DCMAKE_BUILD_TYPE=Debug
        workingDirectory: out/
      - script: source out/emsdk/emsdk_env.sh && script/test_build_emscripten_module.sh
      - script: haxelib --always --quiet install test.hxml
      - script: haxe hxml/test.js.hxml
      - script: source out/emsdk/emsdk_env.sh && python3 script/test_js_headless.py
